apiVersion: v1
kind: Service
metadata:
  name: customerservice
  labels:
    name: customerservice
    app: backend
    visualize: "true"
    uses: microstore
spec:
  type: NodePort
  selector:
    name: microcustomer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
