apiVersion: v1
kind: ReplicationController
metadata:
  name: mongodb-controller
  labels:
    name: mongodb
    visualize: "true"
spec:
  replicas: 1
  selector:
    name: mongodb
  template:
    metadata:
      labels:
        visualize: "true"
        name: mongodb
        app: nosqldb
        uses: mongodb-service
    spec:
      containers:
        - name: mongodb
          image: mongo
          volumeMounts:
            - name: mongodb
              mountPath: /data/db
          ports:
            - name: mongo
              containerPort: 27017
              hostPort: 27017
      volumes:
        - name: mongodb
          gcePersistentDisk:
            pdName: mongodb
            fsType: ext4
