FROM openjdk:alpine
MAINTAINER Olof Markstedt <olofmarkstedt@gmail.com>
ADD target/microStoreSpring-1.0.jar microStoreSpring-1.0.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "/microStoreSpring-1.0.jar"]
