FROM openjdk:alpine
MAINTAINER Olof Markstedt <olofmarkstedt@gmail.com>
ADD target/microCustomerSpring-1.0.jar microCustomerSpring-1.0.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "/microCustomerSpring-1.0.jar"]
